home:
    path:     /
    defaults: { _controller: KodifyBlogBundle:Posts:index }
authors:
    path:     /authors
    defaults: { _controller: KodifyBlogBundle:Authors:index }
create_post:
    path:     /posts/create
    defaults: { _controller: KodifyBlogBundle:Posts:create }
view_post:
    path:     /posts/{id}
    defaults: { _controller: KodifyBlogBundle:Posts:view }
create_author:
    path:     /create
    defaults: { _controller: KodifyUserBundle:Registration:register }

# Comments
create_comment:
    path:     /comments/create/{id}
    defaults: { _controller: KodifyBlogBundle:Comments:create }